"""empty message

Revision ID: 35e988a2ad9b
Revises: befeeb58ea15
Create Date: 2022-05-23 00:14:45.262803

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '35e988a2ad9b'
down_revision = 'befeeb58ea15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'puzzle', 'puzzle', ['puzzle'], ['puzzle'])
    op.alter_column('stats', 'time',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('stats', 'puzzle',
               existing_type=sqlite.JSON(),
               nullable=False)
    op.drop_index('ix_stats_finishTime', table_name='stats')
    op.drop_index('ix_stats_startTime', table_name='stats')
    op.drop_column('stats', 'finishTime')
    op.drop_column('stats', 'difficulty')
    op.drop_column('stats', 'startTime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stats', sa.Column('startTime', sa.DATETIME(), nullable=True))
    op.add_column('stats', sa.Column('difficulty', sa.VARCHAR(length=140), nullable=True))
    op.add_column('stats', sa.Column('finishTime', sa.DATETIME(), nullable=True))
    op.create_index('ix_stats_startTime', 'stats', ['startTime'], unique=False)
    op.create_index('ix_stats_finishTime', 'stats', ['finishTime'], unique=False)
    op.alter_column('stats', 'puzzle',
               existing_type=sqlite.JSON(),
               nullable=True)
    op.alter_column('stats', 'time',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'puzzle', type_='foreignkey')
    # ### end Alembic commands ###
