"""empty message

Revision ID: af709abc9b79
Revises: ba9855661a0b
Create Date: 2022-05-23 19:59:42.922577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af709abc9b79'
down_revision = 'ba9855661a0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stats', type_='foreignkey')
    op.drop_column('stats', 'username')
    op.drop_column('stats', 'user_name')
    op.drop_column('stats', 'userid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stats', sa.Column('userid', sa.INTEGER(), nullable=True))
    op.add_column('stats', sa.Column('user_name', sa.VARCHAR(), nullable=True))
    op.add_column('stats', sa.Column('username', sa.VARCHAR(), nullable=True))
    op.create_foreign_key(None, 'stats', 'user', ['username'], ['username'])
    # ### end Alembic commands ###
