"""empty message

Revision ID: ba9855661a0b
Revises: d6a558234288
Create Date: 2022-05-23 16:50:04.829383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba9855661a0b'
down_revision = 'd6a558234288'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stats', sa.Column('user_name', sa.String(), nullable=True))
    op.add_column('stats', sa.Column('userid', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'stats', type_='foreignkey')
    op.drop_constraint(None, 'stats', type_='foreignkey')
    op.create_foreign_key(None, 'stats', 'user', ['userid'], ['id'])
    op.create_foreign_key(None, 'stats', 'user', ['user_name'], ['username'])
    op.drop_column('stats', 'user_id')
    op.drop_column('stats', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stats', sa.Column('username', sa.VARCHAR(), nullable=True))
    op.add_column('stats', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'stats', type_='foreignkey')
    op.drop_constraint(None, 'stats', type_='foreignkey')
    op.create_foreign_key(None, 'stats', 'user', ['username'], ['username'])
    op.create_foreign_key(None, 'stats', 'user', ['user_id'], ['id'])
    op.drop_column('stats', 'userid')
    op.drop_column('stats', 'user_name')
    # ### end Alembic commands ###
