"""empty message

Revision ID: be2cf50b0bae
Revises: d6de307001bd
Create Date: 2022-05-23 12:29:22.973080

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'be2cf50b0bae'
down_revision = 'd6de307001bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('puzzle')
    op.add_column('stats', sa.Column('username', sa.String(length=64), nullable=False))
    op.alter_column('stats', 'time',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index('ix_stats_finishTime', table_name='stats')
    op.drop_index('ix_stats_startTime', table_name='stats')
    op.create_foreign_key(None, 'stats', 'user', ['username'], ['username'])
    op.drop_column('stats', 'finishTime')
    op.drop_column('stats', 'difficulty')
    op.drop_column('stats', 'puzzle')
    op.drop_column('stats', 'startTime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stats', sa.Column('startTime', sa.DATETIME(), nullable=True))
    op.add_column('stats', sa.Column('puzzle', sqlite.JSON(), nullable=True))
    op.add_column('stats', sa.Column('difficulty', sa.VARCHAR(length=140), nullable=True))
    op.add_column('stats', sa.Column('finishTime', sa.DATETIME(), nullable=True))
    op.drop_constraint(None, 'stats', type_='foreignkey')
    op.create_index('ix_stats_startTime', 'stats', ['startTime'], unique=False)
    op.create_index('ix_stats_finishTime', 'stats', ['finishTime'], unique=False)
    op.alter_column('stats', 'time',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('stats', 'username')
    op.create_table('puzzle',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('puzzle', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
